#!/system/bin/sh

#mount debug filesystem
mount -t debugfs debugfs /sys/kernel/debug 

#Mount system for alsa config
mount -o rw,remount /system
alsa_ctl restore mtsndcard

#Full Access To ALSA
chmod 777 /dev/snd/*;
chown 0.0 /dev/snd/*;

#Using ALSA Drivers
export AUDIODRIVER=alsa;
setprop AUDIODRIVER alsa;
setprop ro.sound.driver alsa;

mount -o ro,remount /system

#Extra Properties
setprop audio.converter.samplerate.preferred libsamplerate;
setprop audio.converter.samplerate.libsamplerate.quality zero_order;
setprop default.pcm.rate_converter samplerate_zero_order;
setprop af.resampler.quality 255

# alsa: suspend/wakeup ALSA devices
echo "89alsa"

case "$1" in
hibernate|suspend)
;;
thaw|resume)
aplay -d 1 /dev/zero
;;
*) exit $NA
;;
esac

chmod 666 /dev/snd/*

echo "alsa enabled."